trigger:
- master
- rel/*

jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'

  variables: 
    BuildConfiguration: Release
    ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    AndroidNdkDirectory: C:\Microsoft\AndroidNDK64\android-ndk-r16b 

  steps:
  
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.2.0'

  - task: nventiveCanaryUpdater@5
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: 'Windows Community Toolkit.sln'
      usePrivateFeed: false
      useNuGetOrg: true
      mergeBranch: true
      branchToMerge: 'uno'
      nugetUpdaterVersion: '2.0.2'
      allowDowngrade: true
      packageAuthor: 'nventive'
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/update_result.json'

  - task: BatchScript@1
    inputs:
      filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
      arguments: -no_logo
      modifyEnvironment: true
    displayName: Setup Environment Variables
    
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 5.6.0
    inputs:
      versionSpec: 5.6.0

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'
    displayName: Use .NET Core SDK 3.1.101

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.103'
    displayName: Use .NET SDK 5.0.103

  - task: DotNetCoreCLI@2  
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool
  
  - script: nbgv cloud
    displayName: Set Version
    
  - powershell: .\build\build.ps1 -target=Package
    displayName: Build 
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: .\bin\nupkg
      artifactType: container
      artifactName: WCT-Packages
    condition: always()

- job: linux

  container: unoplatform/wasm-build:2.3

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.2.0'

  - task: nventiveCanaryUpdater@5
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: 'Windows Community Toolkit.sln'
      usePrivateFeed: false
      useNuGetOrg: true
      mergeBranch: true
      branchToMerge: 'uno'
      nugetUpdaterVersion: '2.0.4'
      allowDowngrade: true
      packageAuthor: 'nventive'
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/update_result.json'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'
    displayName: Use .NET Core SDK 3.1.101

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.103'
    displayName: Use .NET SDK 5.0.103

  - bash: |
      cd $(build.sourcesdirectory)/Microsoft.Toolkit.Uwp.SampleApp.Wasm
      dotnet msbuild /r /nr:false /m:1 /p:Configuration=Release /p:UnoUIUseRoslynSourceGenerators=false /p:UnoUIVersionOverride=true $(build.sourcesdirectory)/Microsoft.Toolkit.Uwp.SampleApp.Wasm/Microsoft.Toolkit.Uwp.SampleApp.Wasm.csproj /p:TargetFrameworksOverride=netstandard2.0 /bl:$(build.artifactstagingdirectory)/build.binlog

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/Microsoft.Toolkit.Uwp.SampleApp.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: wct-aot-drop
      ArtifactType: Container